config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailsender.urls', namespace='mailsender')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailsender/urls.py
from django.urls import path
from mailsender.apps import MailsenderConfig
from mailsender.views import *

app_name = MailsenderConfig.name

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('clients/', ClientManagementListView.as_view(), name='clients_list'),
    path('clients/new/', ClientManagementCreateView.as_view(), name='client_form'),
    path('clients/<int:pk>/', ClientManagementDetailView.as_view(), name='client_detail'),
    path('clients/update/<int:pk>/', ClientManagementUpdateView.as_view(), name='client_update'),
    path('clients/delete/<int:pk>/', ClientManagementDeleteView.as_view(), name='client_confirm_delete'),

    path('messages/', MessageListView.as_view(), name='messages_list'),
    path('messages/new/', MessageCreateView.as_view(), name='message_form'),
    path('messages/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('messages/update/<int:pk>/', MessageUpdateView.as_view(), name='message_update'),
    path('messages/delete/<int:pk>/', MessageDeleteView.as_view(), name='message_confirm_delete'),

    path('mailings/', MailingListView.as_view(), name='mailings_list'),
    path('mailings/new/', MailingCreateView.as_view(), name='mailing_form'),
    path('mailings/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailings/update/<int:pk>/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailings/delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_confirm_delete'),

    path('mailings/<int:pk>/send/', MailingSendView.as_view(), name='send_mailing'),

    path('mailings/<int:mailing_id>/attempts/', MailingAttemptListView.as_view(), name='mailing_attempts'),
]

mailsender/models.py
from django.db import models


class ClientManagement(models.Model):
    email = models.EmailField(max_length=100, unique=True, verbose_name='Электронная почта')
    full_name = models.CharField(max_length=150, verbose_name='Ф. И. О.')
    comment = models.TextField(verbose_name='Комментарий', null=True, blank=True)

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Получатель рассылки'
        verbose_name_plural = 'Получатели рассылки'


class Message(models.Model):
    subject = models.CharField(max_length=200, verbose_name='Тема письма')
    body = models.TextField(verbose_name='Содержание письма')

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Mailing(models.Model):
    COMPLETED = 'Completed'
    CREATED = 'Created'
    LAUNCHED = 'Launched'

    dispatch_status = [
        (COMPLETED, 'Завершена'),
        (CREATED, 'Создана'),
        (LAUNCHED, 'Запущена'),
    ]

    first_sending = models.DateTimeField(verbose_name='Дата отправки первого письма', auto_now_add=True)
    end_sending = models.DateTimeField(verbose_name='Дата окончания отправки', auto_now=True)
    status = models.CharField(max_length=20, choices=dispatch_status, default=CREATED, verbose_name='Статус')
    message = models.ForeignKey(Message, on_delete=models.CASCADE)
    addressees = models.ManyToManyField(ClientManagement)

    def __str__(self):
        message_subject = self.message.subject if self.message else "Без темы"
        return f'{message_subject} {self.status}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'


class MailingAttempt(models.Model):
    SUCCESS = 'success'
    FAILED = 'failed'

    status_choices = [
        (SUCCESS, 'успешно'),
        (FAILED, 'не успешно')
    ]

    attempt_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата и время попытки")
    status = models.CharField(max_length=10, choices=status_choices, verbose_name='Статус')
    server_answer = models.TextField(verbose_name='Ответ почтового сервера')
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.mailing}: {self.status} ({self.attempt_at})'

    class Meta:
        verbose_name = 'Попытка рассылки'
        verbose_name_plural = 'Попытки рассылки'

mailsender/forms.py
from django import forms
from .models import ClientManagement, Message, Mailing, MailingAttempt


class ClientManagementForm(forms.ModelForm):
    class Meta:
        model = ClientManagement
        fields = ['email', 'full_name', 'comment']

    def __init__(self, *args, **kwargs):
        super(ClientManagementForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Введите электронную почту'})
        self.fields['full_name'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Введите Ф. И. О.'})
        self.fields['comment'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Введите комментарий'})


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['subject', 'body']

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        self.fields['subject'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Введите тему письма'})
        self.fields['body'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Введите содержание письма'})


class MailingForm(forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ['message', 'addressees']

    def __init__(self, *args, **kwargs):
        super(MailingForm, self).__init__(*args, **kwargs)
        self.fields['message'].widget.attrs.update({'class': 'form-control'})
        self.fields['addressees'].widget.attrs.update({'class': 'form-check'})


class MailingAttemptForm(forms.ModelForm):
    class Meta:
        model = MailingAttempt
        fields = ['status', 'mailing']

    def __init__(self, *args, **kwargs):
        super(MailingAttemptForm, self).__init__(*args, **kwargs)
        self.fields['status'].widget.attrs.update({'class': 'form-control'})
        self.fields['mailing'].widget.attrs.update({'class': 'form-control'})

mailsender/views.py
from django.conf import settings
from django.core.mail import send_mail, BadHeaderError
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .forms import ClientManagementForm
from .models import ClientManagement, Message, Mailing, MailingAttempt


class HomeView(ListView):
    model = Mailing
    template_name = 'mailsender/home.html'
    context_object_name = 'home_data'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_mailings'] = Mailing.objects.count()
        context['active_mailings'] = Mailing.objects.filter(status=Mailing.LAUNCHED).count()
        context['unique_recipients'] = ClientManagement.objects.values('email').distinct().count()
        return context


class ClientManagementListView(ListView):
    model = ClientManagement
    template_name = 'mailsender/clients_list.html'
    context_object_name = 'clients'


class ClientManagementCreateView(CreateView):
    model = ClientManagement
    fields = ['full_name', 'email']
    template_name = 'mailsender/client_form.html'
    success_url = reverse_lazy('mailsender:clients_list')

    def client_create(request):
        if request.method == 'POST':
            form = ClientManagementForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('clients_list')
        else:
            form = ClientManagementForm()
        return render(request, 'client_form.html', {'form': form})

    def client_update(request, pk):
        client = get_object_or_404(ClientManagement, pk=pk)  # Изменено на ClientManagement
        if request.method == 'POST':
            form = ClientManagementForm(request.POST, instance=client)
            if form.is_valid():
                form.save()
                return redirect('clients_list')
        else:
            form = ClientManagementForm(instance=client)
        return render(request, 'client_form.html', {'form': form})


class ClientManagementDetailView(DetailView):
    model = ClientManagement
    template_name = 'mailsender/client_detail.html'
    context_object_name = 'client'


class ClientManagementUpdateView(UpdateView):
    model = ClientManagement
    fields = ['full_name', 'email']
    template_name = 'mailsender/client_form.html'
    success_url = reverse_lazy('mailsender:clients_list')


class ClientManagementDeleteView(DeleteView):
    model = ClientManagement
    template_name = 'mailsender/client_confirm_delete.html'
    success_url = reverse_lazy('mailsender:clients_list')


class MessageListView(ListView):
    model = Message
    template_name = 'mailsender/messages_list.html'
    context_object_name = 'messages'


class  MessageDetailView(DetailView):
    model = Message
    template_name = 'mailsender/message_detail.html'
    context_object_name = 'message'


class MessageCreateView(CreateView):
    model = Message
    fields = ['subject', 'body']
    template_name = 'mailsender/message_form.html'
    success_url = reverse_lazy('mailsender:messages_list')


class MessageUpdateView(UpdateView):
    model = Message
    fields = ['subject', 'body']
    template_name = 'mailsender/message_form.html'
    success_url = reverse_lazy('mailsender:messages_list')


class MessageDeleteView(DeleteView):
    model = Message
    template_name = 'mailsender/message_confirm_delete.html'
    success_url = reverse_lazy('mailsender:messages_list')


class MailingListView(ListView):
    model = Mailing
    template_name = 'mailsender/mailings_list.html'
    context_object_name = 'mailings'


class MailingDetailView(DetailView):
    model = Mailing
    template_name = 'mailsender/mailing_detail.html'
    context_object_name = 'mailing'


class MailingCreateView(CreateView):
    model = Mailing
    fields = ['status', 'message', 'addressees']
    template_name = 'mailsender/mailing_form.html'
    success_url = reverse_lazy('mailsender:mailings_list')


class MailingUpdateView(UpdateView):
    model = Mailing
    fields = ['status', 'message']
    template_name = 'mailsender/mailing_form.html'
    success_url = reverse_lazy('mailsender:mailings_list')


class MailingDeleteView(DeleteView):
    model = Mailing
    template_name = 'mailsender/mailing_confirm_delete.html'
    success_url = reverse_lazy('mailsender:mailings_list')


class MailingSendView(View):
    def post(self, request, pk):
        mailing = get_object_or_404(Mailing, pk=pk)
        self.send_emails(mailing)
        self.update_status(mailing, Mailing.LAUNCHED)
        return redirect('mailsender:mailings_list')

    def send_emails(self, mailing):
        recipients = [recipient.email for recipient in mailing.addressees.all()]
        for receiver in recipients:
            try:
                send_mail(
                    subject=mailing.message.subject,
                    message=mailing.message.body,
                    from_email=settings.DEFAULT_FROM_EMAIL,
                    recipient_list=[receiver],
                    fail_silently=False,
                )
                MailingAttempt.objects.create(
                    mailing=mailing,
                    status="Success",
                    server_answer=f"Email sent to {receiver}"
                )
            except BadHeaderError:
                self.handle_exception("Invalid header found.", receiver, mailing)
            except Exception as e:
                self.handle_exception(str(e), receiver, mailing)

    def handle_exception(self, error_message, receiver, mailing):
        MailingAttempt.objects.create(
            mailing=mailing,
            status="Failed",
            server_answer=f'Error occurred: "{error_message}" when sending to {receiver}',
        )

    def update_status(self, mailing, status):
        if mailing.status != status:
            mailing.status = status
            mailing.save()


class MailingAttemptListView(ListView):
    model = MailingAttempt
    template_name = "mailsender/mailing_attempts_list.html"
    context_object_name = "mailing_attempts"
    ordering = ["-attempt_at"]

    def get_queryset(self):
        mailing_id = self.kwargs.get("mailing_id")
        return MailingAttempt.objects.filter(mailing__id=mailing_id).order_by("-attempt_at")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mailing_id = self.kwargs.get("mailing_id")
        context['mailing'] = get_object_or_404(Mailing, id=mailing_id)
        return context

mailsender/templates/mailsender/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Главная страница{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% include 'mailsender/header.html' %}

    <main class="container mt-4">
        {% block content %}
        {% endblock %}
    </main>

    <footer class="text-center mt-4">
        <p>&copy; 2025 Система рассылки</p>
    </footer>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

mailsender/templates/mailsender/client_confirm_delete.html
{% extends 'mailsender/base.html' %}

{% block title %}Подтверждение удаления{% endblock %}

{% block content %}
    <h1>Подтверждение удаления клиента</h1>
    <p>Вы уверены, что хотите удалить клиента {{ client.full_name }}?</p>
    <form method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
    </form>
    <a href="{% url 'mailsender:clients_list' %}" class="btn btn-secondary">Отмена</a>
{% endblock %}

mailsender/templates/mailsender/client_detail.html
{% extends 'mailsender/base.html' %}

{% block title %}Детали клиента{% endblock %}

{% block content %}
    <h1>Детали клиента</h1>
    <p><strong>Email:</strong> {{ client.email }}</p>
    <p><strong>Ф. И. О.:</strong> {{ client.full_name }}</p>
    <p><strong>Комментарий:</strong> {{ client.comment }}</p>
    <a href="{% url 'mailsender:clients_list' %}" class="btn btn-secondary">Назад к списку</a>
    <a href="{% url 'mailsender:client_update' client.pk %}" class="btn btn-warning">Редактировать</a>
    <a href="{% url 'mailsender:client_confirm_delete' client.pk %}" class="btn btn-danger">Удалить</a>
{% endblock %}

mailsender/templates/mailsender/client_update.html
{% extends 'mailsender/base.html' %}

{% block title %}Добавить/Редактировать клиента{% endblock %}

{% block content %}
    <h1>{% if form.instance.pk %}Редактировать{% else %}Добавить{% endif %} клиента</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Сохранить</button>
    </form>
    <a href="{% url 'mailsender:clients_list' %}" class="btn btn-secondary">Назад к списку</a>
{% endblock %}

mailsender/templates/mailsender/clients_list.html
{% extends 'mailsender/base.html' %}

{% block title %}Список клиентов{% endblock %}

{% block content %}
    <h1>Список клиентов</h1>
    <a href="{% url 'mailsender:client_form' %}" class="btn btn-primary">Добавить клиента</a>
    <table class="table">
        <thead>
            <tr>
                <th>Email</th>
                <th>Ф. И. О.</th>
                <th>Комментарий</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            {% for client in clients %}
                <tr>
                    <td>{{ client.email }}</td>
                    <td>{{ client.full_name }}</td>
                    <td>{{ client.comment }}</td>
                    <td>
                        <a href="{% url 'mailsender:client_detail' client.pk %}" class="btn btn-info">Просмотр</a>
                        <a href="{% url 'mailsender:client_update' client.pk %}" class="btn btn-warning">Редактировать</a>
                        <a href="{% url 'mailsender:client_confirm_delete' client.pk %}" class="btn btn-danger">Удалить</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

mailsender/templates/mailsender/home.html
{% extends 'mailsender/base.html' %}

{% block title %}Главная страница{% endblock %}

{% block content %}
    <h1>Добро пожаловать!</h1>
    <p>Количество всех рассылок: {{ total_mailings }}</p>
    <p>Количество активных рассылок: {{ active_mailings }}</p>
    <p>Количество уникальных получателей: {{ unique_recipients }}</p>
{% endblock %}

mailsender/templates/mailsender/mailing_attempts_list.html
{% extends 'mailsender/base.html' %}

{% block title %}Попытки рассылки{% endblock %}

{% block content %}
    <h1>Попытки рассылки: {{ mailing.message.subject }}</h1>
    <p><strong>Статус рассылки:</strong> {{ mailing.get_status_display }}</p>
    <table class="table">
        <thead>
            <tr>
                <th>Дата и время попытки</th>
                <th>Статус</th>
                <th>Ответ почтового сервера</th>
            </tr>
        </thead>
        <tbody>
            {% if mailing_attempts.count > 0 %}
                {% for attempt in mailing_attempts %}
                    <tr>
                        <td>{{ attempt.attempt_at }}</td>
                        <td>{{ attempt.get_status_display }}</td>  <!-- Используем get_status_display для отображения читаемого статуса -->
                        <td>{{ attempt.server_answer }}</td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="3">Нет попыток рассылки.</td>
                </tr>
            {% endif %}
        </tbody>
    </table>
    <a href="{% url 'mailsender:mailings_list' %}" class="btn btn-secondary">Назад к списку рассылок</a>
{% endblock %}

mailsender/templates/mailsender/mailing_confirm_delete.html
{% extends 'mailsender/base.html' %}

{% block title %}Подтверждение удаления рассылки{% endblock %}

{% block content %}
    <h1>Подтверждение удаления рассылки</h1>
    <p>Вы уверены, что хотите удалить рассылку "{{ mailing.message.subject }}"?</p>
    <form method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
    </form>
    <a href="{% url 'mailsender:mailings_list' %}" class="btn btn-secondary">Отмена</a>
{% endblock %}

mailsender/templates/mailsender/mailing_detail.html
{% extends 'mailsender/base.html' %}

{% block title %}Детали рассылки{% endblock %}

{% block content %}
    <h1>Детали рассылки</h1>
    <p><strong>Тема сообщения:</strong> {{ mailing.message.subject }}</p>
    <p><strong>Статус:</strong> {{ mailing.get_status_display }}</p>
    <p><strong>Дата и время первой отправки:</strong> {{ mailing.first_sending }}</p>
    <p><strong>Дата и время окончания отправки:</strong> {{ mailing.end_sending }}</p>
     <p><strong>Получатели:</strong>
        {% if mailing.addressees.count > 0 %}
            <ul>
            {% for recipient in mailing.addressees.all %}
                <li>{{ recipient.full_name }} ({{ recipient.email }})</li>
            {% endfor %}
            </ul>
        {% else %}
            Нет получателей.
        {% endif %}
    </p>
    <a href="{% url 'mailsender:mailing_attempts' mailing.pk %}" class="btn btn-primary">Отправить рассылку</a>
    <a href="{% url 'mailsender:mailing_update' mailing.pk %}" class="btn btn-warning">Редактировать</a>
    <a href="{% url 'mailsender:mailing_confirm_delete' mailing.pk %}" class="btn btn-danger">Удалить</a>
    <a href="{% url 'mailsender:mailings_list' %}" class="btn btn-secondary">Назад к списку</a>

{% endblock %}

mailsender/templates/mailsender/mailings_list.html
{% extends 'mailsender/base.html' %}

{% block title %}Список рассылок{% endblock %}

{% block content %}
    <h1>Список рассылок</h1>
    <a href="{% url 'mailsender:mailing_form' %}" class="btn btn-primary">Добавить рассылку</a>
    <table class="table">
        <thead>
            <tr>
                <th>Тема сообщения</th>
                <th>Статус</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            {% for mailing in mailings %}
                <tr>
                    <td>{{ mailing.message.subject }}</td>
                    <td>{{ mailing.get_status_display }}</td>
                    <td>
                        <a href="{% url 'mailsender:mailing_detail' mailing.pk %}" class="btn btn-info">Просмотр</a>
                        <a href="{% url 'mailsender:mailing_update' mailing.pk %}" class="btn btn-warning">Редактировать</a>
                        <a href="{% url 'mailsender:mailing_confirm_delete' mailing.pk %}" class="btn btn-danger">Удалить</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

mailsender/templates/mailsender/message_detail.html
{% extends 'mailsender/base.html' %}

{% block title %}Детали сообщения{% endblock %}

{% block content %}
    <h1>Детали сообщения</h1>
    <p><strong>Тема письма:</strong> {{ message.subject }}</p>
    <p><strong>Тело письма:</strong> {{ message.body }}</p>
    <a href="{% url 'mailsender:messages_list' %}" class="btn btn-secondary">Назад к списку</a>
    <a href="{% url 'mailsender:message_update' message.pk %}" class="btn btn-warning">Редактировать</a>
    <a href="{% url 'mailsender:message_confirm_delete' message.pk %}" class="btn btn-danger">Удалить</a>
{% endblock %}

mailsender/templates/mailsender/message_form.html
{% extends 'mailsender/base.html' %}

{% block title %}Добавить/Редактировать сообщение{% endblock %}

{% block content %}
    <h1>{% if form.instance.pk %}Редактировать{% else %}Добавить{% endif %} сообщение</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Сохранить</button>
    </form>
    <a href="{% url 'mailsender:messages_list' %}" class="btn btn-secondary">Назад к списку</a>
{% endblock %}

mailsender/templates/mailsender/messages_list.html
{% extends 'mailsender/base.html' %}

{% block title %}Список сообщений{% endblock %}

{% block content %}
    <h1>Список сообщений</h1>
    <a href="{% url 'mailsender:message_form' %}" class="btn btn-primary">Добавить сообщение</a>
    <table class="table">
        <thead>
            <tr>
                <th>Тема письма</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            {% for message in messages %}
                <tr>
                    <td>{{ message.subject }}</td>
                    <td>
                        <a href="{% url 'mailsender:message_detail' message.pk %}" class="btn btn-info">Просмотр</a>
                        <a href="{% url 'mailsender:message_update' message.pk %}" class="btn btn-warning">Редактировать</a>
                        <a href="{% url 'mailsender:message_confirm_delete' message.pk %}" class="btn btn-danger">Удалить</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

mailsender/templates/mailsender/send_mailing.html
{% extends 'base.html' %}

{% block title %}Отправка рассылки{% endblock %}

{% block content %}
    <h1>Отправка рассылки: {{ mailing.message.subject }}</h1>
    <p>Получатели:</p>
    <ul>
        {% for recipient in mailing.addressees.all %}
            <li>{{ recipient.full_name }} ({{ recipient.email }})</li>
        {% endfor %}
    </ul>
    <form method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-success">Отправить рассылку</button>
    </form>
    <a href="{% url 'mailsender:mailings_list' %}" class="btn btn-secondary">Назад к списку</a>
{% endblock %}